# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\tugasADA\tubesada.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from random import randint
from math import floor

class Ui_tubes(object):
    def setupUi(self, tubes):
        tubes.setObjectName("tubes")
        tubes.resize(520, 572)
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        tubes.setFont(font)
        self.groupBox = QtWidgets.QGroupBox(tubes)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 131, 211))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.jumlah_b = QtWidgets.QSpinBox(self.groupBox)
        self.jumlah_b.setGeometry(QtCore.QRect(60, 30, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jumlah_b.setFont(font)
        self.jumlah_b.setProperty("value", 0)
        self.jumlah_b.setObjectName("jumlah_b")
        self.jumlah_c = QtWidgets.QSpinBox(self.groupBox)
        self.jumlah_c.setGeometry(QtCore.QRect(60, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jumlah_c.setFont(font)
        self.jumlah_c.setObjectName("jumlah_c")
        self.jumlah_d = QtWidgets.QSpinBox(self.groupBox)
        self.jumlah_d.setGeometry(QtCore.QRect(60, 90, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jumlah_d.setFont(font)
        self.jumlah_d.setObjectName("jumlah_d")
        self.jumlah_e = QtWidgets.QSpinBox(self.groupBox)
        self.jumlah_e.setGeometry(QtCore.QRect(60, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jumlah_e.setFont(font)
        self.jumlah_e.setObjectName("jumlah_e")
        self.jumlah_f = QtWidgets.QSpinBox(self.groupBox)
        self.jumlah_f.setGeometry(QtCore.QRect(60, 150, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jumlah_f.setFont(font)
        self.jumlah_f.setObjectName("jumlah_f")
        self.jumlah_g = QtWidgets.QSpinBox(self.groupBox)
        self.jumlah_g.setGeometry(QtCore.QRect(60, 180, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jumlah_g.setFont(font)
        self.jumlah_g.setObjectName("jumlah_g")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 180, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox_2 = QtWidgets.QGroupBox(tubes)
        self.groupBox_2.setGeometry(QtCore.QRect(150, 50, 361, 211))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(100, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.jarak_aa = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_aa.setEnabled(False)
        self.jarak_aa.setGeometry(QtCore.QRect(50, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_aa.setFont(font)
        self.jarak_aa.setObjectName("jarak_aa")
        self.jarak_ab = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ab.setGeometry(QtCore.QRect(90, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ab.setFont(font)
        self.jarak_ab.setObjectName("jarak_ab")
        self.jarak_ac = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ac.setGeometry(QtCore.QRect(130, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ac.setFont(font)
        self.jarak_ac.setObjectName("jarak_ac")
        self.jarak_ad = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ad.setGeometry(QtCore.QRect(170, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ad.setFont(font)
        self.jarak_ad.setObjectName("jarak_ad")
        self.jarak_ae = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ae.setGeometry(QtCore.QRect(210, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ae.setFont(font)
        self.jarak_ae.setObjectName("jarak_ae")
        self.jarak_af = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_af.setGeometry(QtCore.QRect(250, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_af.setFont(font)
        self.jarak_af.setObjectName("jarak_af")
        self.jarak_ag = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ag.setGeometry(QtCore.QRect(290, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ag.setFont(font)
        self.jarak_ag.setObjectName("jarak_ag")
        self.jarak_ba = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ba.setGeometry(QtCore.QRect(50, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ba.setFont(font)
        self.jarak_ba.setObjectName("jarak_ba")
        self.jarak_bc = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_bc.setGeometry(QtCore.QRect(130, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_bc.setFont(font)
        self.jarak_bc.setObjectName("jarak_bc")
        self.jarak_bd = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_bd.setGeometry(QtCore.QRect(170, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_bd.setFont(font)
        self.jarak_bd.setObjectName("jarak_bd")
        self.jarak_bf = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_bf.setGeometry(QtCore.QRect(250, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_bf.setFont(font)
        self.jarak_bf.setObjectName("jarak_bf")
        self.jarak_bb = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_bb.setEnabled(False)
        self.jarak_bb.setGeometry(QtCore.QRect(90, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_bb.setFont(font)
        self.jarak_bb.setObjectName("jarak_bb")
        self.jarak_bg = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_bg.setGeometry(QtCore.QRect(290, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_bg.setFont(font)
        self.jarak_bg.setObjectName("jarak_bg")
        self.jarak_be = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_be.setGeometry(QtCore.QRect(210, 60, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_be.setFont(font)
        self.jarak_be.setObjectName("jarak_be")
        self.jarak_ca = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ca.setGeometry(QtCore.QRect(50, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ca.setFont(font)
        self.jarak_ca.setObjectName("jarak_ca")
        self.jarak_cc = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_cc.setEnabled(False)
        self.jarak_cc.setGeometry(QtCore.QRect(130, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_cc.setFont(font)
        self.jarak_cc.setObjectName("jarak_cc")
        self.jarak_dc = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_dc.setGeometry(QtCore.QRect(130, 100, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_dc.setFont(font)
        self.jarak_dc.setObjectName("jarak_dc")
        self.jarak_df = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_df.setGeometry(QtCore.QRect(250, 100, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_df.setFont(font)
        self.jarak_df.setObjectName("jarak_df")
        self.jarak_cd = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_cd.setGeometry(QtCore.QRect(170, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_cd.setFont(font)
        self.jarak_cd.setObjectName("jarak_cd")
        self.jarak_da = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_da.setGeometry(QtCore.QRect(50, 100, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_da.setFont(font)
        self.jarak_da.setObjectName("jarak_da")
        self.jarak_cf = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_cf.setGeometry(QtCore.QRect(250, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_cf.setFont(font)
        self.jarak_cf.setObjectName("jarak_cf")
        self.jarak_cb = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_cb.setGeometry(QtCore.QRect(90, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_cb.setFont(font)
        self.jarak_cb.setObjectName("jarak_cb")
        self.jarak_db = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_db.setGeometry(QtCore.QRect(90, 100, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_db.setFont(font)
        self.jarak_db.setObjectName("jarak_db")
        self.jarak_dd = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_dd.setEnabled(False)
        self.jarak_dd.setGeometry(QtCore.QRect(170, 100, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_dd.setFont(font)
        self.jarak_dd.setObjectName("jarak_dd")
        self.jarak_cg = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_cg.setGeometry(QtCore.QRect(290, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_cg.setFont(font)
        self.jarak_cg.setObjectName("jarak_cg")
        self.jarak_de = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_de.setGeometry(QtCore.QRect(210, 100, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_de.setFont(font)
        self.jarak_de.setObjectName("jarak_de")
        self.jarak_ce = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ce.setGeometry(QtCore.QRect(210, 80, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ce.setFont(font)
        self.jarak_ce.setObjectName("jarak_ce")
        self.jarak_dg = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_dg.setGeometry(QtCore.QRect(290, 100, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_dg.setFont(font)
        self.jarak_dg.setObjectName("jarak_dg")
        self.jarak_ff = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ff.setEnabled(False)
        self.jarak_ff.setGeometry(QtCore.QRect(250, 140, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ff.setFont(font)
        self.jarak_ff.setObjectName("jarak_ff")
        self.jarak_eg = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_eg.setGeometry(QtCore.QRect(290, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_eg.setFont(font)
        self.jarak_eg.setObjectName("jarak_eg")
        self.jarak_gc = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_gc.setGeometry(QtCore.QRect(130, 160, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_gc.setFont(font)
        self.jarak_gc.setObjectName("jarak_gc")
        self.jarak_fe = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_fe.setGeometry(QtCore.QRect(210, 140, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_fe.setFont(font)
        self.jarak_fe.setObjectName("jarak_fe")
        self.jarak_ee = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ee.setEnabled(False)
        self.jarak_ee.setGeometry(QtCore.QRect(210, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ee.setFont(font)
        self.jarak_ee.setObjectName("jarak_ee")
        self.jarak_fb = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_fb.setGeometry(QtCore.QRect(90, 140, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_fb.setFont(font)
        self.jarak_fb.setObjectName("jarak_fb")
        self.jarak_fd = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_fd.setGeometry(QtCore.QRect(170, 140, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_fd.setFont(font)
        self.jarak_fd.setObjectName("jarak_fd")
        self.jarak_gf = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_gf.setGeometry(QtCore.QRect(250, 160, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_gf.setFont(font)
        self.jarak_gf.setObjectName("jarak_gf")
        self.jarak_gg = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_gg.setEnabled(False)
        self.jarak_gg.setGeometry(QtCore.QRect(290, 160, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_gg.setFont(font)
        self.jarak_gg.setObjectName("jarak_gg")
        self.jarak_fg = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_fg.setGeometry(QtCore.QRect(290, 140, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_fg.setFont(font)
        self.jarak_fg.setObjectName("jarak_fg")
        self.jarak_gb = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_gb.setGeometry(QtCore.QRect(90, 160, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_gb.setFont(font)
        self.jarak_gb.setObjectName("jarak_gb")
        self.jarak_fa = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_fa.setGeometry(QtCore.QRect(50, 140, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_fa.setFont(font)
        self.jarak_fa.setObjectName("jarak_fa")
        self.jarak_gd = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_gd.setGeometry(QtCore.QRect(170, 160, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_gd.setFont(font)
        self.jarak_gd.setObjectName("jarak_gd")
        self.jarak_fc = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_fc.setGeometry(QtCore.QRect(130, 140, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_fc.setFont(font)
        self.jarak_fc.setObjectName("jarak_fc")
        self.jarak_ea = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ea.setGeometry(QtCore.QRect(50, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ea.setFont(font)
        self.jarak_ea.setObjectName("jarak_ea")
        self.jarak_ef = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ef.setGeometry(QtCore.QRect(250, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ef.setFont(font)
        self.jarak_ef.setObjectName("jarak_ef")
        self.jarak_ge = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ge.setGeometry(QtCore.QRect(210, 160, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ge.setFont(font)
        self.jarak_ge.setObjectName("jarak_ge")
        self.jarak_eb = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_eb.setGeometry(QtCore.QRect(90, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_eb.setFont(font)
        self.jarak_eb.setObjectName("jarak_eb")
        self.jarak_ga = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ga.setGeometry(QtCore.QRect(50, 160, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ga.setFont(font)
        self.jarak_ga.setObjectName("jarak_ga")
        self.jarak_ec = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ec.setGeometry(QtCore.QRect(130, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ec.setFont(font)
        self.jarak_ec.setObjectName("jarak_ec")
        self.jarak_ed = QtWidgets.QSpinBox(self.groupBox_2)
        self.jarak_ed.setGeometry(QtCore.QRect(170, 120, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.jarak_ed.setFont(font)
        self.jarak_ed.setObjectName("jarak_ed")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(60, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(140, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(180, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(220, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(260, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(300, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(30, 40, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(30, 60, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(30, 80, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(30, 100, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(30, 120, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(30, 140, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(30, 160, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_3 = QtWidgets.QGroupBox(tubes)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 341, 80))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(20, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.waktu_pengobatan = QtWidgets.QSpinBox(self.groupBox_3)
        self.waktu_pengobatan.setGeometry(QtCore.QRect(20, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.waktu_pengobatan.setFont(font)
        self.waktu_pengobatan.setObjectName("waktu_pengobatan")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(70, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.waktu_perjalanan = QtWidgets.QSpinBox(self.groupBox_3)
        self.waktu_perjalanan.setGeometry(QtCore.QRect(190, 40, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.waktu_perjalanan.setFont(font)
        self.waktu_perjalanan.setObjectName("waktu_perjalanan")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(190, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(240, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.button_submit = QtWidgets.QPushButton(tubes)
        self.button_submit.setGeometry(QtCore.QRect(360, 310, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.button_submit.setFont(font)
        self.button_submit.setAutoFillBackground(False)
        self.button_submit.setStyleSheet("background-color:rgb(0, 255, 127)")
        self.button_submit.setObjectName("button_submit")
        self.groupBox_4 = QtWidgets.QGroupBox(tubes)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 360, 501, 151))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.hasil_rute_terbaik = QtWidgets.QLineEdit(self.groupBox_4)
        self.hasil_rute_terbaik.setGeometry(QtCore.QRect(20, 40, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        self.hasil_rute_terbaik.setFont(font)
        self.hasil_rute_terbaik.setText("")
        self.hasil_rute_terbaik.setAlignment(QtCore.Qt.AlignCenter)
        self.hasil_rute_terbaik.setReadOnly(True)
        self.hasil_rute_terbaik.setObjectName("hasil_rute_terbaik")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(20, 80, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.hasil_waktu_jam = QtWidgets.QLineEdit(self.groupBox_4)
        self.hasil_waktu_jam.setGeometry(QtCore.QRect(20, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(16)
        self.hasil_waktu_jam.setFont(font)
        self.hasil_waktu_jam.setText("")
        self.hasil_waktu_jam.setAlignment(QtCore.Qt.AlignCenter)
        self.hasil_waktu_jam.setReadOnly(True)
        self.hasil_waktu_jam.setObjectName("hasil_waktu_jam")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(330, 110, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.hasil_waktu_menit = QtWidgets.QLineEdit(self.groupBox_4)
        self.hasil_waktu_menit.setGeometry(QtCore.QRect(200, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(16)
        self.hasil_waktu_menit.setFont(font)
        self.hasil_waktu_menit.setText("")
        self.hasil_waktu_menit.setAlignment(QtCore.Qt.AlignCenter)
        self.hasil_waktu_menit.setReadOnly(True)
        self.hasil_waktu_menit.setObjectName("hasil_waktu_menit")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(150, 110, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(tubes)
        self.label_29.setGeometry(QtCore.QRect(10, 10, 501, 20))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(tubes)
        self.label_30.setGeometry(QtCore.QRect(10, 540, 501, 20))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(tubes)
        self.label_31.setGeometry(QtCore.QRect(10, 520, 501, 20))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.button_isi_otomatis = QtWidgets.QPushButton(tubes)
        self.button_isi_otomatis.setGeometry(QtCore.QRect(360, 280, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_isi_otomatis.setFont(font)
        self.button_isi_otomatis.setStyleSheet("background-color:rgb(255, 255, 127)")
        self.button_isi_otomatis.setObjectName("button_isi_otomatis")
        self.button_acak = QtWidgets.QPushButton(tubes)
        self.button_acak.setGeometry(QtCore.QRect(450, 280, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Google Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_acak.setFont(font)
        self.button_acak.setStyleSheet("background-color:rgb(255, 170, 255)")
        self.button_acak.setObjectName("button_acak")

        self.retranslateUi(tubes)
        QtCore.QMetaObject.connectSlotsByName(tubes)

        self.button_isi_otomatis.clicked.connect(self.tekan_isi_otomatis)
        self.button_acak.clicked.connect(self.tekan_acak)
        self.button_submit.clicked.connect(self.tekan_submit)

    def retranslateUi(self, tubes):
        _translate = QtCore.QCoreApplication.translate
        tubes.setWindowTitle(_translate("tubes", "Tugas Besar - Analisis dan Desain Algoritma"))
        self.groupBox.setTitle(_translate("tubes", "Jumlah Groupies"))
        self.label.setText(_translate("tubes", "B"))
        self.label_2.setText(_translate("tubes", "C"))
        self.label_3.setText(_translate("tubes", "D"))
        self.label_4.setText(_translate("tubes", "E"))
        self.label_5.setText(_translate("tubes", "F"))
        self.label_6.setText(_translate("tubes", "G"))
        self.groupBox_2.setTitle(_translate("tubes", "Jarak"))
        self.label_7.setText(_translate("tubes", "B"))
        self.label_8.setText(_translate("tubes", "A"))
        self.label_9.setText(_translate("tubes", "C"))
        self.label_10.setText(_translate("tubes", "D"))
        self.label_11.setText(_translate("tubes", "E"))
        self.label_12.setText(_translate("tubes", "F"))
        self.label_13.setText(_translate("tubes", "G"))
        self.label_14.setText(_translate("tubes", "A"))
        self.label_15.setText(_translate("tubes", "B"))
        self.label_16.setText(_translate("tubes", "C"))
        self.label_17.setText(_translate("tubes", "D"))
        self.label_18.setText(_translate("tubes", "E"))
        self.label_19.setText(_translate("tubes", "F"))
        self.label_20.setText(_translate("tubes", "G"))
        self.groupBox_3.setTitle(_translate("tubes", "Waktu"))
        self.label_21.setText(_translate("tubes", "Pengobatan"))
        self.label_22.setText(_translate("tubes", "menit/orang"))
        self.label_23.setText(_translate("tubes", "Perjalanan"))
        self.label_24.setText(_translate("tubes", "menit/jarak"))
        self.button_submit.setText(_translate("tubes", "Cari Jalur Optimal"))
        self.groupBox_4.setTitle(_translate("tubes", "Hasil"))
        self.label_25.setText(_translate("tubes", "Rute Terbaik"))
        self.label_26.setText(_translate("tubes", "Waktu yang akan ditempuh"))
        self.label_27.setText(_translate("tubes", "Menit"))
        self.label_28.setText(_translate("tubes", "Jam"))
        self.label_29.setText(_translate("tubes", "Pencarian Jalur Optimal menggunakan Algoritma Greedy"))
        self.label_30.setText(_translate("tubes", "Copyright 2018 - S1 Teknik Informatika 2016 off B - Universitas Negeri Malang"))
        self.label_31.setText(_translate("tubes", "M. Fandi Arfabuma - Siti Fatimah Puspitaningrum - Siti Nur Khofifah"))
        self.button_isi_otomatis.setText(_translate("tubes", "Isi Otomatis"))
        self.button_acak.setText(_translate("tubes", "Acak"))

    def tekan_isi_otomatis(self):
        self.jumlah_b.setValue(2)
        self.jumlah_c.setValue(4)
        self.jumlah_d.setValue(5)
        self.jumlah_e.setValue(1)
        self.jumlah_f.setValue(2)
        self.jumlah_g.setValue(3)

        self.jarak_ab.setValue(6)
        self.jarak_ac.setValue(4)
        self.jarak_ad.setValue(4)
        self.jarak_ae.setValue(20)
        self.jarak_af.setValue(12)
        self.jarak_ag.setValue(8)
        self.jarak_ba.setValue(self.jarak_ab.value())
        self.jarak_bc.setValue(4)
        self.jarak_bd.setValue(6)
        self.jarak_be.setValue(7)
        self.jarak_bf.setValue(4)
        self.jarak_bg.setValue(12)
        self.jarak_ca.setValue(self.jarak_ac.value())
        self.jarak_cb.setValue(self.jarak_bc.value())
        self.jarak_cd.setValue(12)
        self.jarak_ce.setValue(8)
        self.jarak_cf.setValue(9)
        self.jarak_cg.setValue(4)
        self.jarak_da.setValue(self.jarak_ad.value())
        self.jarak_db.setValue(self.jarak_bd.value())
        self.jarak_dc.setValue(self.jarak_cd.value())
        self.jarak_de.setValue(3)
        self.jarak_df.setValue(5)
        self.jarak_dg.setValue(12)
        self.jarak_ea.setValue(self.jarak_ae.value())
        self.jarak_eb.setValue(self.jarak_be.value())
        self.jarak_ec.setValue(self.jarak_ce.value())
        self.jarak_ed.setValue(self.jarak_de.value())
        self.jarak_ef.setValue(8)
        self.jarak_eg.setValue(8)
        self.jarak_fa.setValue(self.jarak_af.value())
        self.jarak_fb.setValue(self.jarak_bf.value())
        self.jarak_fc.setValue(self.jarak_cf.value())
        self.jarak_fd.setValue(self.jarak_df.value())
        self.jarak_fe.setValue(self.jarak_ef.value())
        self.jarak_fg.setValue(5)
        self.jarak_ga.setValue(self.jarak_ag.value())
        self.jarak_gb.setValue(self.jarak_bg.value())
        self.jarak_gc.setValue(self.jarak_cg.value())
        self.jarak_gd.setValue(self.jarak_dg.value())
        self.jarak_ge.setValue(self.jarak_eg.value())
        self.jarak_gf.setValue(self.jarak_fg.value())

        self.waktu_pengobatan.setValue(5)
        self.waktu_perjalanan.setValue(10)
    
    def tekan_acak(self):
        self.jumlah_b.setValue(randint(1,5))
        self.jumlah_c.setValue(randint(1,5))
        self.jumlah_d.setValue(randint(1,5))
        self.jumlah_e.setValue(randint(1,5))
        self.jumlah_f.setValue(randint(1,5))
        self.jumlah_g.setValue(randint(1,5))

        self.jarak_ab.setValue(randint(5,20))
        self.jarak_ac.setValue(randint(5,20))
        self.jarak_ad.setValue(randint(5,20))
        self.jarak_ae.setValue(randint(5,20))
        self.jarak_af.setValue(randint(5,20))
        self.jarak_ag.setValue(randint(5,20))
        self.jarak_ba.setValue(self.jarak_ab.value())
        self.jarak_bc.setValue(randint(5,20))
        self.jarak_bd.setValue(randint(5,20))
        self.jarak_be.setValue(randint(5,20))
        self.jarak_bf.setValue(randint(5,20))
        self.jarak_bg.setValue(randint(5,20))
        self.jarak_ca.setValue(self.jarak_ac.value())
        self.jarak_cb.setValue(self.jarak_bc.value())
        self.jarak_cd.setValue(randint(5,20))
        self.jarak_ce.setValue(randint(5,20))
        self.jarak_cf.setValue(randint(5,20))
        self.jarak_cg.setValue(randint(5,20))
        self.jarak_da.setValue(self.jarak_ad.value())
        self.jarak_db.setValue(self.jarak_bd.value())
        self.jarak_dc.setValue(self.jarak_cd.value())
        self.jarak_de.setValue(randint(5,20))
        self.jarak_df.setValue(randint(5,20))
        self.jarak_dg.setValue(randint(5,20))
        self.jarak_ea.setValue(self.jarak_ae.value())
        self.jarak_eb.setValue(self.jarak_be.value())
        self.jarak_ec.setValue(self.jarak_ce.value())
        self.jarak_ed.setValue(self.jarak_de.value())
        self.jarak_ef.setValue(randint(5,20))
        self.jarak_eg.setValue(randint(5,20))
        self.jarak_fa.setValue(self.jarak_af.value())
        self.jarak_fb.setValue(self.jarak_bf.value())
        self.jarak_fc.setValue(self.jarak_cf.value())
        self.jarak_fd.setValue(self.jarak_df.value())
        self.jarak_fe.setValue(self.jarak_ef.value())
        self.jarak_fg.setValue(randint(5,20))
        self.jarak_ga.setValue(self.jarak_ag.value())
        self.jarak_gb.setValue(self.jarak_bg.value())
        self.jarak_gc.setValue(self.jarak_cg.value())
        self.jarak_gd.setValue(self.jarak_dg.value())
        self.jarak_ge.setValue(self.jarak_eg.value())
        self.jarak_gf.setValue(self.jarak_fg.value())

        self.waktu_pengobatan.setValue(randint(5,10))
        self.waktu_perjalanan.setValue(randint(10,20))
    
    def rute_greedy(self,G,G2,pos_awal_akhir,wo,wp):
        hasil = []
        hasil.append(pos_awal_akhir)

        cost_time = 0

        while len(hasil) < len(G):
            posisi_now = hasil[-1]
            
            for z in hasil:
                if z in G[posisi_now]:
                    del G[posisi_now][z]

            posisi_next = [key for key in G[posisi_now].keys() if G[posisi_now][key]==min(G[posisi_now].values())]
            if len(posisi_next) > 1:
                x = {}
                for y in posisi_next:
                    x[y] = G2[y]
                
                posisi_next = [key for key in x.keys() if x[key]==min(x.values())]

            posisi_next = ''.join(posisi_next)
            hasil.append(posisi_next)

            cost_time = cost_time + (G[posisi_now][posisi_next] * wp) + (G2[posisi_next] * wo)
        
        cost_time = cost_time + (G[hasil[-1]][pos_awal_akhir] * wp)
        hasil.append(pos_awal_akhir)

        return [hasil,cost_time]

    def tekan_submit(self):
        T = {
            'B': self.jumlah_b.value(),
            'C': self.jumlah_c.value(),
            'D': self.jumlah_d.value(),
            'E': self.jumlah_e.value(),
            'F': self.jumlah_f.value(),
            'G': self.jumlah_g.value(),
        }
        
        R = {
            'A': {
                'B': self.jarak_ab.value(),
                'C': self.jarak_ac.value(),
                'D': self.jarak_ad.value(),
                'E': self.jarak_ae.value(),
                'F': self.jarak_af.value(),
                'G': self.jarak_ag.value()},
            'B': {
                'A': self.jarak_ba.value(),
                'C': self.jarak_bc.value(),
                'D': self.jarak_bd.value(),
                'E': self.jarak_be.value(),
                'F': self.jarak_bf.value(),
                'G': self.jarak_bg.value()},
            'C': {
                'A': self.jarak_ca.value(),
                'B': self.jarak_cb.value(),
                'D': self.jarak_cd.value(),
                'E': self.jarak_ce.value(),
                'F': self.jarak_cf.value(),
                'G': self.jarak_cg.value()},
            'D': {
                'A': self.jarak_da.value(),
                'B': self.jarak_db.value(),
                'C': self.jarak_dc.value(),
                'E': self.jarak_de.value(),
                'F': self.jarak_df.value(),
                'G': self.jarak_dg.value()},
            'E': {
                'A': self.jarak_ea.value(),
                'B': self.jarak_eb.value(),
                'C': self.jarak_ec.value(),
                'D': self.jarak_ed.value(),
                'F': self.jarak_ef.value(),
                'G': self.jarak_eg.value()},
            'F': {
                'A': self.jarak_fa.value(),
                'B': self.jarak_fb.value(),
                'C': self.jarak_fc.value(),
                'D': self.jarak_fd.value(),
                'E': self.jarak_fe.value(),
                'G': self.jarak_fg.value()},
            'G': {
                'A': self.jarak_ga.value(),
                'B': self.jarak_gb.value(),
                'C': self.jarak_gc.value(),
                'D': self.jarak_gd.value(),
                'E': self.jarak_ge.value(),
                'F': self.jarak_gf.value()}
        }

        rG = self.rute_greedy(R,T,'A', self.waktu_pengobatan.value(), self.waktu_perjalanan.value())

        w_jam = floor(rG[1] / 60)
        w_menit = (rG[1] % 60)

        
        self.hasil_rute_terbaik.setText(str(' -> '.join(rG[0])))
        self.hasil_waktu_jam.setText(str(w_jam))
        self.hasil_waktu_menit.setText(str(w_menit))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tubes = QtWidgets.QDialog()
    ui = Ui_tubes()
    ui.setupUi(tubes)
    tubes.show()
    sys.exit(app.exec_())

